### ISSUE TITLE
Duplicate "了" in naïve mode

### ISSUE THREAD

**Issue by tonyxty** [PhotonQuantum/hithit_bot#1]
/喵喵了
Expected: [Tony Beta Lambda](https://github.com/tonyxty/) 喵喵了 [自己](https://github.com/tonyxty/)！
Got: [Tony Beta Lambda](https://github.com/tonyxty/) 喵喵了了 [自己](https://github.com/tonyxty/)！

**Comment by PhotonQuantum** [comment]
![4002FD18-8EE9-4236-8E13-4E5366A19698](https://user-images.githubusercontent.com/18749973/108984863-59163b80-76cb-11eb-9a2a-d228c35179f7.png)
