### ISSUE TITLE
Extra sender at beginning of message when using extended formatting

### ISSUE THREAD

**Issue by tonyxty** [PhotonQuantum/hithit_bot#3]
/{sender} 打打了 {receiver}
Expected: [Tony Beta Lambda](https://github.com/tonyxty/) 打打了 [自己](https://github.com/tonyxty/)！
Got: [Tony Beta Lambda](https://github.com/tonyxty/) [Tony Beta Lambda](https://github.com/tonyxty/) 打打了 [自己](https://github.com/tonyxty/)！

**Comment by PhotonQuantum** [comment]
Maybe we should remove the prefix ident in curly formatting mode?
